// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1-8C0AQq9fqeTX2nX8iC-8PLLGGgk-yw',
    appId: '1:382821611392:web:2b2b0a0b2a2bd5bfe3b365',
    messagingSenderId: '382821611392',
    projectId: 'kiitattendance-21',
    authDomain: 'kiitattendance-21.firebaseapp.com',
    storageBucket: 'kiitattendance-21.firebasestorage.app',
    measurementId: 'G-SVNLJX8595',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-m4-Swpg79qsWDvXXsFizMpDSI3MkELQ',
    appId: '1:382821611392:android:b960497981195eaae3b365',
    messagingSenderId: '382821611392',
    projectId: 'kiitattendance-21',
    storageBucket: 'kiitattendance-21.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz_wZcJgTQuMIBWCH5PIEOAGCyVWulKis',
    appId: '1:382821611392:ios:21b92cf0b18a29fee3b365',
    messagingSenderId: '382821611392',
    projectId: 'kiitattendance-21',
    storageBucket: 'kiitattendance-21.firebasestorage.app',
    iosClientId: '382821611392-n678pquih6f6kn7vphhfcpobreft99mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAttendanceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz_wZcJgTQuMIBWCH5PIEOAGCyVWulKis',
    appId: '1:382821611392:ios:21b92cf0b18a29fee3b365',
    messagingSenderId: '382821611392',
    projectId: 'kiitattendance-21',
    storageBucket: 'kiitattendance-21.firebasestorage.app',
    iosClientId: '382821611392-n678pquih6f6kn7vphhfcpobreft99mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1-8C0AQq9fqeTX2nX8iC-8PLLGGgk-yw',
    appId: '1:382821611392:web:2b2b0a0b2a2bd5bfe3b365',
    messagingSenderId: '382821611392',
    projectId: 'kiitattendance-21',
    authDomain: 'kiitattendance-21.firebaseapp.com',
    storageBucket: 'kiitattendance-21.firebasestorage.app',
    measurementId: 'G-SVNLJX8595',
  );
}
